### ISSUE TITLE
Github = Modhub Version?

### ISSUE THREAD

**Issue by MeRida2104** [tn4799/FS19_limitedDailyIncome#10]
Hi @tn4799 , die Version im Modhub trägt die Version 1.0.1.0, das letzte Github Release ist 1.0.0.2.

Wie sieht es mit dem derzeitigen Code aus? Basiert dieser auf 1.0.1.0? 

Beste Grüße
MeRida

**Comment by tn4799** [comment]
Hi.
Der Code im github repo (nicht der release) ist etwas neuer als der modhub release. Zumindest wenn ich die changelog in der moddesc hier auf github richtig gelesen hab.
