### ISSUE TITLE
Error with Mod and MIssions

### ISSUE THREAD

**Issue by SushiPirate** [tn4799/FS19_limitedDailyIncome#6]
Hello, 

we want to play with this mord. But from the start there is a lua Method error, so u cant start missions even with zero income used. Can u help us?

Best regard 

Sushi

**Comment by tn4799** [comment]
Please post your log.txt file. This file is located at C:/Users/_user_/Documents/My Games/FarmingSimulator2022/log.txt.

When you have posted your log file I can help you to find the problem.

**Comment by SushiPirate** [comment]
[log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/8717430/log.txt)
![Screenshot_1](https://user-images.githubusercontent.com/105593547/169075803-ea634ab9-088d-43de-bfe0-c5f1521e647c.jpg)
HEy there is the Log. I cant find the ingame error in the log so ive done a screenshot. Its in MP and SP

**Comment by tn4799** [comment]
Could you please send your log.txt file.
In there are a lot more informations for me.

**Comment by SushiPirate** [comment]
ive send it in the first answer

**Comment by SushiPirate** [comment]
[log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/8718077/log.txt)

**Comment by SushiPirate** [comment]
the second was in sp, but the blacksceen appears also in mp
[log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/8718107/log.txt)

**Comment by SushiPirate** [comment]
[log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/8718254/log.txt)

**Comment by tn4799** [comment]
I've fixed it. 
You can find the new version as a Release, just download the FS22_limitedDailyIncome.zip.
