### ISSUE TITLE
No Missions available

### ISSUE THREAD

**Issue by dietzus** [tn4799/FS19_limitedDailyIncome#7]
Hello,

we currently tried to use your mod on our 24/7 server but whenever we try to accept/activate a mission there is simply nothing happening. No error message or anything.

When i coded some debug messages into the function i saw that the numbers (current money and limit) are correct so the superfunction should be called i think yet nothing is happening.

Is this a known problem and is there something we could try to do?

We use the most recent version of farming simulator 2022 and this problem is both in multiplayer and singleplayer.

**Comment by dietzus** [comment]
I just saw the Issue#6 which had the same problem as we have (we also get a black screen if we exit the running game to the main menu)

Attached you find both logs for the server and for my machine, the logs are only from a short time, i connected to the server, attempted to accept one mission with vehicles, attempted to accept a mission without vehicles, did the same for another mission and then tried to exit to the main menu which resulted in a black screen that i terminated with Alt+F4.

I hope this helps in finding the problem.
[log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/9173997/log.txt)
[server_log.txt](https://github.com/tn4799/FS19_limitedDailyIncome/files/9173998/server_log.txt)

**Comment by dietzus** [comment]
Okay, nevermind, i totally didn't see that it is version 1.0.0.0 on modhub which does NOT have fixes from Issue#6 in them, i used the code from github (v1.0.0.1) now and it seems to work, we can start missions now but still get a black screen when going back to the main menu, but that doesn't matter too much to us since we usually end it with Alt+F4 anyways.

**Comment by tn4799** [comment]
Thanks for reporting the bug with the black screen. I've fixed it and created a new release where this bug is fixed.
